language: csharp  

platform:
    # будем гонять CI на amd64 и x86...
    - x64
    - x86

configuration:
    # ... и в дебажной, и в релизной конфигурациях ...
    - Debug
    - Release

environment:
    matrix:
        # ... на трёх студиях (2010, 2012, 2015)
        - TOOLCHAIN: msvc10
        - TOOLCHAIN: msvc12
        - TOOLCHAIN: msvc14
